---
title: "Bot"
author: "Zach Austin"
date: "5/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

rm(list=ls())

```

```{r}


project_name = 'mlb_odds_trends'

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
repo_path = file.path(substr(getwd(),0,gregexpr(pattern = project_name ,
                                                getwd())[[1]][1]-2),
                      project_name)

source(file.path(repo_path,
                 'code',
                 'utilities',
                 'load_directories.r'),
       local = knitr::knit_global())

p <- c("tidyverse",
       "httr",
       "lubridate",
       "ggplot2"
)

load_all_packages(p)

source(file.path(objects_path,'odds_functions.r'))


```

# Read Data
- See Sports Data Collection / MLB / Pregame Lines

```{r}

tidy_data = read.csv(file.path(data_in,'action','tidy.csv'))

```

## Clean Data

### Timezone adjustment

```{r}

hour_adj = hours(4)

tidy_data$GAME_TIME = as_datetime(tidy_data$GAME_TIME) - hour_adj

tidy_data$GAME_DATE = as.Date(tidy_data$GAME_TIME)

```


# Caclulate Result Metrics

Results Needed:
- FG/F5
  - ATS
  - Over / Under

```{r}



```


# Check for Insights

## League Trends

```{r}

names(res_data)

```

### O / U by Team

```{r}

# O_U_by_team
v1 = res_data %>% 
  select(GAME_DATE,TEAM_NAME,FG_OU,FG_OVER_UNITS,FG_UNDER_UNITS,OPP_PITCHER_THROW) %>% 
  group_by(TEAM_NAME,OPP_PITCHER_THROW) %>% 
  summarize(FG_O_PROFIT = sum(FG_OVER_UNITS),
            FG_U_PROFIT = sum(FG_UNDER_UNITS),
            FG_O = sum(ifelse(FG_OU=="OVER",1,0)),
            FG_U = sum(ifelse(FG_OU=="UNDER",1,0)),
            FG_P = sum(ifelse(FG_OU=="PUSH",1,0)))
  
  
write.csv(v1,file.path(data_in,'insights','O_U_by_team.csv'),row.names = F)

```

### ATS by Team

```{r}

v2 = res_data %>% 
  select(GAME_DATE,TEAM_NAME,FG_ATS,FG_ATS_UNITS,FG_SPREAD_PRICE,OPP_PITCHER_THROW) %>% 
  group_by(TEAM_NAME,OPP_PITCHER_THROW) %>% 
  summarize(ATS_PROFIT = sum(FG_ATS_UNITS),
            ATS_W = sum(ifelse(FG_ATS=="WIN",1,0), na.rm = T),
            ATS_L = sum(ifelse(FG_ATS=="LOSE",1,0), na.rm = T),
            ATS_P = sum(ifelse(FG_ATS=="PUSH",1,0), na.rm = T),
            ATS_W_pct = ATS_W / (ATS_W+ATS_L+ATS_P)
            ) %>% 
  arrange(desc(ATS_PROFIT))

write.csv(v2,file.path(data_in,'insights','ATS_by_team.csv'),row.names = F)

```

### Team vs Pitcher

```{r}

v3 = res_data %>% 
  select(GAME_DATE,TEAM_NAME,FG_RUNS,F5_RUNS,OPP_PITCHER_NAME) %>% 
  group_by(TEAM_NAME,OPP_PITCHER_NAME) %>% 
  summarize(n = n(),
            MED_F5_RUNS = median(F5_RUNS, na.rm = T),
            MED_FG_RUNS = median(FG_RUNS, na.rm = T),
            MEAN_F5_RUNS = mean(F5_RUNS, na.rm = T),
            MEAN_FG_RUNS = mean(FG_RUNS, na.rm = T)) %>% 
  arrange(desc(n))

write.csv(v3,file.path(data_in,'insights',"RUNS_by_team_vs_pitcher.csv"),row.names = F)

```

### Runs by Team

```{r}

v4 = res_data %>% 
  select(GAME_DATE,TEAM_NAME,FG_RUNS,F5_RUNS,OPP_PITCHER_THROW) %>% 
  group_by(TEAM_NAME,OPP_PITCHER_THROW) %>% 
  summarize(n = n(),
            MED_F5_RUNS = median(F5_RUNS, na.rm = T),
            MED_FG_RUNS = median(FG_RUNS, na.rm = T),
            MEAN_F5_RUNS = mean(F5_RUNS, na.rm = T),
            MEAN_FG_RUNS = mean(FG_RUNS, na.rm = T)) %>% 
  arrange(TEAM_NAME)

write.csv(v4,file.path(data_in,'insights',"RUNS_by_team_vs_phand.csv"),row.names = F)

```







